### ISSUE TITLE
ResilientDB Fails to run when clients > 1

### ISSUE THREAD

**Issue by RohanSogani** [resilientdb/resilientdb#1]
@gupta-suyash @sajjadrahnama
./resilientDB-docker --clients=2 --replicas=4
The ./resilientDB-docker fails because the ifconfig file is not created properly. The reason being, multiple clients are added in the same line separated by \n. There is a small bug in the docker-ifconfig.sh file.

I've fixed this small bug in my local copy.

**Comment by gupta-suyash** [comment]
Please send a pull request for the updated file.

**Comment by RohanSogani** [comment]
Hi Suyash,
I've sent a pull request for review.
