### ISSUE TITLE
'NN:: Exception' when trying to run ResilientDB-Docker with large number of clients/replicas

### ISSUE THREAD

**Issue by JuharAhmed** [resilientdb/resilientdb#10]
Dear,
I tried to run resilientDB Blockchain using Docker. It works fine with a small number of clients/servers. However it gives me the error shown on the snapshot below when the number of clients/replicas is >= 10. 
For your information, the following three commands give me the same error:
./resilientDB-docker --clients=10 --replicas=4
./resilientDB-docker --clients=1 --replicas=10
./resilientDB-docker --clients=10 --replicas=10

However, it works fine  if i run it as follows,:
  ./resilientDB-docker --clients=9 --replicas=4 
  ./resilientDB-docker --clients=9 --replicas=9   
    ./resilientDB-docker --clients=1 --replicas=4   
![Capture](https://user-images.githubusercontent.com/12408705/91384153-3d8fbc80-e871-11ea-8214-21309518e7cb.JPG)

**Comment by gupta-suyash** [comment]
@sajjadrahnama, please have a look.

**Comment by sajjadrahnama** [comment]
@JuharAhmed Thanks, it is fixed
