### ISSUE TITLE
Run in a geo-distributed way

### ISSUE THREAD

**Issue by mister-dx7** [resilientdb/resilientdb#12]
Hi authors,

How to run your code on more than 1 cluster? For now, if I use ``./resilientDB-docker --clients=1 --replicas=4`` then I have 1 cluster wit 4 replicas. But I want 2 clusters with 4 replicas in each. I think there must be some configuration to be done because ``./resilientDB-docker --clients=1 --replicas=8`` wont split the replicas in 2 clusters.

Appreciate your help!

**Comment by sajjadrahnama** [comment]
Running in multiple regions or clusters should be done through startResilientDB script located in the scripts folder.
