### ISSUE TITLE
Docker setup script very limiting

### ISSUE THREAD

**Issue by Raycoms** [resilientdb/resilientdb#18]
First of all, it seems the app is only compiled on one of the servers:

```
docker exec s1 mkdir -p obj
docker exec s1 make clean
docker exec s1 make
```
Instead on all, which I do not understand.

Second, a lot of the code connects to the containers and executes commands instead of putting a startscript in the Dockerfile which is then executed after startup. This makes a multi-machine setup with swarm very difficult.

In that sense, the repo is also missing the actual Dockerfile to allow people to setup this kind of thing easily for themselvs.

**Comment by Raycoms** [comment]
Would it be possible to get the Dockerfile that is used to build it?

**Comment by resilientdb** [comment]
deprecated/outdated
