### ISSUE TITLE
What's the DB type (in-memory or SQLite) used in the experiments of VLDB publication

### ISSUE THREAD

**Issue by rum-a** [resilientdb/resilientdb#25]
Dear authors of ResilientDB,

Your VLDB publication _ResilientDB: Global Scale Resilient Blockchain Fabric_ was an excellent one, and I really appreciate that your team kindly open source this great work.

Sorry about spamming the issues of this repo, but may I know which DB (in_memory_db or Sqlite) was used in the experiments of the paper?

Thanks!

**Comment by gupta-suyash** [comment]
We used in_memory db for the paper.
