### ISSUE TITLE
*TRIVIAL* "./resilientdb -d" runs successfully even though there is a problem while running ./rundb

### ISSUE THREAD

**Issue by p-shubham** [resilientdb/resilientdb#3]
Hi, @sajjadrahnama @gupta-suyash @RohanSogani 
Following is the output of execution script in the results folder:
![bug](https://user-images.githubusercontent.com/16755241/69593719-e6418080-0fae-11ea-9564-9d9930f40056.PNG)
(Note: One of the errors that happen if make fails)

Following is the output in the terminal:
![bugpic2](https://user-images.githubusercontent.com/16755241/69593721-e6418080-0fae-11ea-97af-904336915cb9.PNG)

PS: I have docker running on VMWare Player 15 and connected to VS Code installed on my Windows via SSH.

**Comment by gupta-suyash** [comment]
@p-shubham if you have a patch for this send it along. @sajjadrahnama please have a look at this case.

**Comment by p-shubham** [comment]
@gupta-suyash Working on it. Will post.
By the way, It is an intermittent bug.

**Comment by scalettar** [comment]
I don't know if it is the same problem, but I was getting the same output when I ran "./resilientdb -d".

The issue for me was that I had to make sure that my previous docker containers c1, s1, etc from when I set up ExpoDB-BC were not having a name conflict with Resilient when Resilient tried to make new c1, s1, etc.

You can use "docker-compose down" while in the directory of the docker-compose file from ExpoDB (NOT ResilientDB folder). If you already deleted ExpoDB folder when you replaced it with ResilientDB then you will have to find another way to remove the old containers made with ExpoDB so your new ResilientDB containers won't have the naming conflict. You can do this with the Docker extension in VSCode for example. After downloading the extension, click on the Docker tab in the left Activity sidebar. From there you can individually right-click and "stop" and "remove" each container. Then when you run "./resilientdb -d" the problem should be solved.
